name: Build and Deploy to Skynet
on: [push]
jobs:
  build:
    environment: dev
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build-html
      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: out
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🥭 The job's status is ${{ job.status }}."
