name: Build and Deploy to Skynet
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build-html
    - name: Deploy to Skynet
      uses: SkynetLabs/deploy-to-skynet-action@v2
      with:
        upload-dir: out
        github-token: ${{ secrets.GITHUB_TOKEN }}
        registry-seed: ${{ secrets.REGISTRY_SEED || '' }}
        registry-datakey: ${{ secrets.REGISTRY_DATAKEY || '' }}
    - run: echo "🥭 The job's status is ${{ job.status }}."